title: 无敌网
description: > # this means to ignore newlines until "baseurl:"
  无敌网 - 未来之网
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://5dw.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 5dw # add your name
author-img: 5dw.png # add your photo
about-author: <div><b>无敌网</b></div>未来之网,网尽人间百味;<br/>五维之网,网尽古今南北。 # add description
#twitter: # add your Twitter handle
#facebook: # add your Facebook handle
github: 5dw # add your Github handle
#linkedin: # add your Linkedin handle
email: x.zhiquan@gmail.com # add your Email address

# Disqus
discus-identifier: 5dw # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
